### ISSUE TITLE
bug: missing project link of Glific in the website

### ISSUE THREAD

**Issue by jaiakash** [CodeForGoodTech/C4GT#1]
The project link for Glific is missing in the C4GT main website. https://www.codeforgovtech.in/copy-of-projects

Bug video - 
[Screencast from 2023-05-22 01-15-11.webm](https://github.com/Code4GovTech/C4GT/assets/33419526/e95a9754-a134-4102-96cb-bb90b041d01c)

Link to be added: https://github.com/Code4GovTech/C4GT/wiki/Glific

**Comment by ChakshuGautam** [comment]
@bhavyaberlia is this done?

**Comment by ananyabansal16** [comment]
I can make the changes if required.

**Comment by pruthula0** [comment]
This bug has been fixed. The link to Glific has been added to the C4GT main website. It is now working as expected.
