### ISSUE TITLE
na

### ISSUE THREAD

**Issue by venkatramanm** [CodeForGoodTech/C4GT#303]

**Comment by SanjayRam07** [comment]
hello @venkatramanm , @raviprakash , can I work on this issue?
Could you please assign this and mentor me?

**Comment by vaidehiadhi** [comment]
hey there, i have gone through it can i please contribute to this project

**Comment by fatchat** [comment]
Hello this comment is part of the DMP review @SaumyaSamagra @dmp24-c4gt

May I suggest including links to a) beckn documentation, and b) the definitions of BPP and BAP

My feeling is that this issue has quite a bit of initial ramp-up from reading and understanding, but once that's done the implementation should be doable within the timeframe of the DMP

**Comment by AbhimanyuSamagra** [comment]
Do not ask process related questions about how to apply and who to contact in the above ticket. The only questions allowed are about technical aspects of the project itself. If you want help with the process, you can refer instructions listed on [Unstop](https://unstop.com/competitions/dedicated-mentoring-program-dmp-2024-code-for-govtech-932803?lb=7gWXVfKv) and any further queries can be taken up on our [Discord channel](https://discord.com/invite/VPrXf7Jxpr) titled DMP queries.
