### ISSUE TITLE
Architecture of DMP CMS

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#411]
- PRD + Acceptance Criteria + Phases

**Comment by MohitNSamagra** [comment]
[PRD](https://docs.google.com/document/d/193ekwbRehSHepvTM0by05MRGYumGOPG7w-77IUmTOUw/edit)

Acceptance Criteria(Vercel)

- As a user, I am able to view a list of all DMP projects on the vercel website
- As a user, I am able to navigate to the DMP 2024 projects
- As a user, I am able to navigate to the project that I am working on/want to see
- As a user, after clicking on the project, I am able to view an overview of the project with contributor and mentor names, project progress(as a percentage), PRs raised/merged and all the weeks within a project(12)
- As a user, I am able to click on the dropdown of each week to see the detailed tasks, the progress within each week (as a percentage) and the weekly learnings
- As a user, I am able to see changes and updates according to the changes made to the github tickets
- As a user I am able to navigate to the github ticket from the vercel app

**Comment by karntrehan** [comment]
- @karntrehan to share image of architecture diagram.
- Test body HTML contents from the API - body, body_text, body_html - @VedantKhairnar 
- Wireframes of Vercel app. - @MohitNSamagra

**Comment by karntrehan** [comment]
Architecture diagram: 

![Image](https://github.com/Code4GovTech/C4GT/assets/5885669/024ba331-0468-4c3a-9143-3a7a448718f2)

**Comment by karntrehan** [comment]
> As a user, I am able to click on the dropdown of each week to see the detailed tasks, the progress within each week (as a percentage) and the weekly learnings

This might be overkill. We should have a single landing page for each issue with the HTML render of both weekly learnings and goals for the viewer. Progress we can check how to calculate. 

Need wireframes of progress. 

@MohitNSamagra ^

**Comment by MohitNSamagra** [comment]
- Wireframes by early Tue - @MohitNSamagra

**Comment by karntrehan** [comment]
FE being tracked in #413
