### ISSUE TITLE
[BE] Development of Vercel App

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#412]
Basis #411 BE to be picked.

**Comment by karntrehan** [comment]
Local changes done. Repo to be created. Deployment to be done on C4GT prod server.

**Comment by MohitNSamagra** [comment]
- Timestamps for PRs to be added
- Project completion metrics- to be picked up post this

**Comment by MohitNSamagra** [comment]
- Delayed due to #418

**Comment by karntrehan** [comment]
* Flask application done. 
* HTML code selection to be done - HTML URL to be sent in v1, FE to inflate html.
* Dashboard requirement based database changes pending.

**Comment by VedantKhairnar** [comment]
27th May 13:03
- Temporary Deployment Link: [https://dmp-cms-backend-api-5.onrender.com/apidocs/](https://dmp-cms-backend-api-5.onrender.com/apidocs/)
- Will update the response format

**Comment by MohitNSamagra** [comment]
- To be tested through the frontend integration and dashboard @MohitNSamagra

**Comment by karntrehan** [comment]
To change: 

- [x] Fix CORs issue.
- [x] @GET(“/issues/org_id/”) to contain 1 object rather than list. 
- [ ] Change cron job to pull mentor info and save to db
- [x] Change API @GET(“/issues/org_id/issue_id”) 
    - [x] to send mentor details from DB
    - [x] Issue url to be fixed.
    - [x] Change comment link to body_html.
    - [x] Fix PR details inside pr_details issue.

**Comment by MohitNSamagra** [comment]
- [x] Contributor name to be picked from dmp_issues

**Comment by MohitNSamagra** [comment]
- [x] DevOps fixes
- [x] Prod deployment
- [x] Weekly updates and learnings to be picked from a single comment

**Comment by MohitNSamagra** [comment]
- [x] Org name to be picked from db

**Comment by MohitNSamagra** [comment]
- Org name to be picked from db to be completed - Tue

**Comment by karntrehan** [comment]
Tested by Mohit. Is done. Rest development to happen in Phase 2 ticket.
