### ISSUE TITLE
[FE] Development of Vercel App

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#413]
Existing portal: https://c4gt-milestones.vercel.app/docs/2022
Existing code base: https://github.com/Code4GovTech/dmp-documentation

- [ ] React based FE development
- [ ] Integration with BE contracts
- [ ] Deployment

**Comment by MohitNSamagra** [comment]
Attaching the first mockups: 

[DMP CMS .pdf](https://github.com/Code4GovTech/C4GT/files/15306264/DMP.CMS.pdf)

@karntrehan Let us go ahead with the same design but without the dropdowns for the v1. Post that we can work on creating dropdowns to reduce scroll. In the v1, one specific requirement from the team was that the overall PR table for a project should be linked at the top so that one can quickly jump to that as the scroll otherwise will be too long.

**Comment by karntrehan** [comment]
Contracts: https://docs.google.com/document/d/1VM7l7_5p0bPzOuvaK2GgNusNjm2rVhfwaE6TgvJtFkY/edit?usp=sharing

cc @VedantKhairnar

**Comment by MohitNSamagra** [comment]
- Samagra logo to be replaced with the C4GT logo

**Comment by MohitNSamagra** [comment]
- Navigation bar fixes remain
- API integration

**Comment by karntrehan** [comment]
To fix: 

- [x] Contributor name , mentor name - Multiple name fixes.
- [x] Add column for names. 
- [x] Split weekly tasks and weekly learnings.
- [x] Add week to PR table.

Question to product: 

- [ ] Content of PR summary

**Comment by MohitNSamagra** [comment]
- PR summary moved to P2
- Hiding mentor names

**Comment by MohitNSamagra** [comment]
- Mentor names to be shown - added manually to db

**Comment by MohitNSamagra** [comment]
- PR to be merged by Amit

**Comment by MohitNSamagra** [comment]
- @MohitNSamagra to test
