### ISSUE TITLE
Dashboard of DMP CMS

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#414]

**Comment by MohitNSamagra** [comment]
- Delayed due to #412

**Comment by MohitNSamagra** [comment]
- @MohitNSamagra to pick in 2412

**Comment by karntrehan** [comment]
* BE changes done by Sasi
* Call pending with PT to create the dashboard.

**Comment by MohitNSamagra** [comment]
- Call with PT done - metabase dashboard to be made by PT

**Comment by MohitNSamagra** [comment]
- Db reviewed by @MohitNSamagra 
- PT to pick up on 19th June

**Comment by MohitNSamagra** [comment]
- To be picked by PT next week

**Comment by karntrehan** [comment]
Being tested by PT.

**Comment by karntrehan** [comment]
Closing this as no update from PT
