### ISSUE TITLE
[Ad Hoc][Documentation] Github App Tech

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#418]
- [ ] Github app tech documentation(API)

**Comment by karntrehan** [comment]
Draft: https://docs.google.com/document/d/1WJ-94fwLgnQtdWoUishcpIXoHrQKLgVk5suxjPeKamk/edit#heading=h.8qxqg3tqrm9g

* Close the documentation by Monday EOD. 
* Link elements in documentation with blocks in archictecure diagram. 
* @karntrehan + @VedantKhairnar + Sasi to work on this today eod.

**Comment by MohitNSamagra** [comment]
- @VedantKhairnar to transfer to @karntrehan

**Comment by MohitNSamagra** [comment]
- Sent by @karntrehan on Wed, 29th May
