### ISSUE TITLE
DEPRIORITISED: Product Scoping - Auto-merge Repo

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#420]
- Clone of [Pledge App](https://pledge.codeforcause.org/)
- Need Auto-Merge feature(PR gets automatically merged after a build process check)
- https://auto-merge.vercel.app/

**Comment by MohitNSamagra** [comment]
- To be discussed with PT by @MohitNSamagra

**Comment by karntrehan** [comment]
Deprioritised.
