### ISSUE TITLE
[Community] GitHub Authentication

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#425]
**Flow:** 
- A new user lands on the C4GT website
- User navigates to the [community projects page](https://www.codeforgovtech.in/community-program-projects/)
- User clicks on join the community to join the discord server
- User is prompted to answer questions about themselves on discord
- Post this, channels open up which includes an 'authenticate' channel
- User then clicks on the authenticate button to be redirected to GitHub in order to link their Github ID to their discord 

This information is then used by us to award points to different users according to several criterias(there are points for authenticating github as well)

**Bug:** When authenticate is clicked on, the user is redirected but the page keeps on loading and does not open. While a fix was deployed for this, it seems to work on occasionally. PT is looking for a permanent fix to this.

@karntrehan can add tech details of when this was earlier debugged.

**Comment by MohitNSamagra** [comment]
@jaanbaaz understanding codebase

**Comment by MohitNSamagra** [comment]
- code testing to be closed today
- @jaanbaaz to add final rca

**Comment by MohitNSamagra** [comment]
- Server size issue - to be increased
- devops to be included

**Comment by karntrehan** [comment]
Server resized. Services up'ed as well. To be dev tested.

**Comment by MohitNSamagra** [comment]
- permission error - discord bot repo @karntrehan @KDwevedi

**Comment by MohitNSamagra** [comment]
- @KDwevedi to have a look as well

**Comment by MohitNSamagra** [comment]
- Tested on Thursday, Friday - worked but taking a long time to load
- More logs to be added
- To be tested @MohitNSamagra

**Comment by MohitNSamagra** [comment]
- Logs & timestamps added
