### ISSUE TITLE
[Bugs] DMP CMS

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#426]
Unexpected token '<', "<!doctype "... is not valid JSON

- Old vercel link to be removed from documentation/other places

**Comment by MohitNSamagra** [comment]
Current open threads:
1. IDinsight & Shikshalokam-2 tickets not showing up - TBP
2. ⁠The above Arghyam ticket PRs not showing up - TBP
3. ⁠Weekly goals for certain projects (as raised on the dmp contributor group) not showing up - PR raised
4. ⁠Weekly learnings not being displayed correctly (for certain projects as raised on dmp contributor group) -  PR raised
5. ⁠Progress bar not moving even though checkboxes are ticked in one project (as raised on the dmp contributor group)-  PR raised

**Comment by MohitNSamagra** [comment]
- Arghyam - PRs raised before 11th June
- IDinsight: https://github.com/IDinsight/aaq-core/issues/128 changed to https://github.com/IDinsight/ask-a-question/issues/128
- Shikshalokam: https://github.com/ELEVATE-Project/sl-backend-automation/issues/19 repo in db is test-automation-portal(was not changed from earlier)

**Comment by MohitNSamagra** [comment]
IDinsight & Shikshalokam-2 tickets not showing up - db error - tested and closed
⁠The above Arghyam ticket PRs not showing up - TBP
⁠Weekly goals for certain projects (as raised on the dmp contributor group) not showing up - tested and closed
⁠Weekly learnings not being displayed correctly (for certain projects as raised on dmp contributor group) - tested and closed
⁠Progress bar not moving even though checkboxes are ticked in one project (as raised on the dmp contributor group)- tested and closed

**Comment by jaanbaaz** [comment]
Arghyam ticket PRs do not contain issue number in the PR title, so they aren't getting picked

**Comment by MohitNSamagra** [comment]
- Issue ticket numbers to be added to PR titles @MohitNSamagra
