### ISSUE TITLE
[Community Program Dashboard] Audit of Engaged and Active Contributors

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#427]
**Active**

To be merged soon: 599739bd-b253-400e-a042-0b74126b3a12
Raised but not appearing in connected_prs: https://github.com/dhiway/cord/pull/498

**Engaged**

ticket_comments - last one in April

Ticket cycle from creation to pr merging - @jaanbaaz @MohitNSamagra

**Comment by jaanbaaz** [comment]
Raised but not appearing in connected_prs: https://github.com/dhiway/cord/pull/498
the PR title does not contain issue number, hence it isn't getting picked

**Comment by MohitNSamagra** [comment]
- PR review by Sasi, Vedant

**Comment by MohitNSamagra** [comment]
- New access token to be generated and replaced

**Comment by MohitNSamagra** [comment]
https://github.com/SamagraX-Stencil/stencil-ui/issues/7

Mohit commented - comments to be checked

**Comment by MohitNSamagra** [comment]
- PR raising code does not exist - to be added
- Comments- webhook test in progress - @jaanbaaz to update

**Comment by MohitNSamagra** [comment]
- Being tested on staging

**Comment by karntrehan** [comment]
Tested on prod. Done through script. Long term fix in community platform v2 ticket.
