### ISSUE TITLE
[Community] New Github Auth Scoping

### ISSUE THREAD

**Issue by MohitNSamagra** [CodeForGoodTech/C4GT#435]
**Problem** 
Github authentication through the bot redirects users to another link which has many vulnerabilities and often breaks. An alternative needs to be found to allow for linking of discord accounts to github and therefore for faster and more reliable authentication.

**Solution** 
Authentication by manual entry of github username by user.

**Flow/Acceptance Criteria**
1. Once a user has joined the server, he/she navigates to the authentication channel.
2. In chat, user is asked to enter their github username. User enters this and sends it to us.
3. Once received, we send the github API to check whether the user exists.
4. If exists, a 'success' message is returned and this entry is added to the database.
5. If not, user is asked to enter a valid github username.
6. Post this, other channels are opened/restricted according to authentication.

**Comment by jaanbaaz** [comment]
to get users data - https://api.github.com/users/MohitNSamagra

**Comment by jaanbaaz** [comment]
To get users data for Github authentication, a request needs to be sent to https://api.github.com/users/{github_username}. This return data of the Github user in json which can then be used to extract all the necessary details we need.
